# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.taskManager = QtWidgets.QTabWidget(self.centralwidget)
        self.taskManager.setFocusPolicy(QtCore.Qt.TabFocus)
        self.taskManager.setElideMode(QtCore.Qt.ElideMiddle)
        self.taskManager.setDocumentMode(True)
        self.taskManager.setTabsClosable(False)
        self.taskManager.setMovable(True)
        self.taskManager.setTabBarAutoHide(False)
        self.taskManager.setObjectName("taskManager")
        self.task1 = QtWidgets.QWidget()
        self.task1.setObjectName("task1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.task1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.task1)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 2)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.task1)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.task1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.task1)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.task1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.task1)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.task1)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.task1)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.task1)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.task1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 5, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.task1)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.task1)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 2, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.task1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.task1)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.task1)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_13 = QtWidgets.QLabel(self.task1)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.task1)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_4.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.task1)
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.task1)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 2)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.task1)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_4.addWidget(self.lineEdit_8, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 3, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.task1)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.task1)
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout_5.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.taskManager.addTab(self.task1, "")
        self.task2 = QtWidgets.QWidget()
        self.task2.setObjectName("task2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.task2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.focusStacking = QtWidgets.QGridLayout()
        self.focusStacking.setObjectName("focusStacking")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.task2)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 713, 465))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setItalic(True)
        self.image_label.setFont(font)
        self.image_label.setText("")
        self.image_label.setScaledContents(True)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.verticalLayout_2.addWidget(self.image_label)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.focusStacking.addWidget(self.scrollArea_3, 1, 1, 1, 1)
        self.l_button_2 = QtWidgets.QPushButton(self.task2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.l_button_2.setFont(font)
        self.l_button_2.setStyleSheet("border:0px;\n"
"color: black;")
        self.l_button_2.setText("<")
        self.l_button_2.setIconSize(QtCore.QSize(40, 40))
        self.l_button_2.setObjectName("l_button_2")
        self.focusStacking.addWidget(self.l_button_2, 1, 0, 1, 1)
        self.filename_label = QtWidgets.QLabel(self.task2)
        self.filename_label.setObjectName("filename_label")
        self.focusStacking.addWidget(self.filename_label, 0, 1, 1, 1)
        self.r_button_2 = QtWidgets.QPushButton(self.task2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.r_button_2.setFont(font)
        self.r_button_2.setStyleSheet("border:0px;\n"
"color: black;")
        self.r_button_2.setObjectName("r_button_2")
        self.focusStacking.addWidget(self.r_button_2, 1, 2, 1, 1)
        self.gridLayout_6.addLayout(self.focusStacking, 0, 0, 1, 1)
        self.taskManager.addTab(self.task2, "")
        self.task4 = QtWidgets.QWidget()
        self.task4.setObjectName("task4")
        self.gridLayout = QtWidgets.QGridLayout(self.task4)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.task4)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.task4Grid = QtWidgets.QGridLayout(self.layoutWidget)
        self.task4Grid.setContentsMargins(0, 0, 0, 0)
        self.task4Grid.setObjectName("task4Grid")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.layoutWidget)
        self.scrollArea_5.setMinimumSize(QtCore.QSize(800, 600))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 798, 598))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image_label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label_2.sizePolicy().hasHeightForWidth())
        self.image_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setItalic(True)
        self.image_label_2.setFont(font)
        self.image_label_2.setText("")
        self.image_label_2.setScaledContents(True)
        self.image_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_2.setObjectName("image_label_2")
        self.verticalLayout_3.addWidget(self.image_label_2)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_4)
        self.task4Grid.addWidget(self.scrollArea_5, 1, 1, 1, 1)
        self.l_button_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.l_button_3.setFont(font)
        self.l_button_3.setStyleSheet("border:0px;\n"
"color: black;")
        self.l_button_3.setText("<")
        self.l_button_3.setIconSize(QtCore.QSize(40, 40))
        self.l_button_3.setObjectName("l_button_3")
        self.task4Grid.addWidget(self.l_button_3, 1, 0, 1, 1)
        self.filename_label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.filename_label_2.setObjectName("filename_label_2")
        self.task4Grid.addWidget(self.filename_label_2, 0, 1, 1, 1)
        self.r_button_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.r_button_3.setFont(font)
        self.r_button_3.setStyleSheet("border:0px;\n"
"color: black;")
        self.r_button_3.setObjectName("r_button_3")
        self.task4Grid.addWidget(self.r_button_3, 1, 2, 1, 1)
        self.formLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.longLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.longLabel.setObjectName("longLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.longLabel)
        self.longitudeEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.longitudeEdit.setObjectName("longitudeEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.longitudeEdit)
        self.latLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.latLabel.setObjectName("latLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.latLabel)
        self.latitudeEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.latitudeEdit.setObjectName("latitudeEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.latitudeEdit)
        self.altLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.altLabel.setObjectName("altLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.altLabel)
        self.altitudeEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.altitudeEdit.setObjectName("altitudeEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.altitudeEdit)
        self.rollLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.rollLabel.setObjectName("rollLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.rollLabel)
        self.rollEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rollEdit.setObjectName("rollEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.rollEdit)
        self.pitchLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.pitchLabel.setObjectName("pitchLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pitchLabel)
        self.pitchEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.pitchEdit.setObjectName("pitchEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pitchEdit)
        self.yawLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.yawLabel.setObjectName("yawLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.yawLabel)
        self.yawEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.yawEdit.setObjectName("yawEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.yawEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 2000, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        self.addButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.addButton.setObjectName("addButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.addButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.taskManager.addTab(self.task4, "")
        self.task5 = QtWidgets.QWidget()
        self.task5.setObjectName("task5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.task5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.photochanges = QtWidgets.QGridLayout()
        self.photochanges.setObjectName("photochanges")
        self.l_button = QtWidgets.QPushButton(self.task5)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.l_button.setFont(font)
        self.l_button.setStyleSheet("border:0px;\n"
"color: black;")
        self.l_button.setObjectName("l_button")
        self.photochanges.addWidget(self.l_button, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.task5)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 351, 487))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.firstimages = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstimages.sizePolicy().hasHeightForWidth())
        self.firstimages.setSizePolicy(sizePolicy)
        self.firstimages.setText("")
        self.firstimages.setScaledContents(True)
        self.firstimages.setObjectName("firstimages")
        self.horizontalLayout_2.addWidget(self.firstimages)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.photochanges.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.r_button = QtWidgets.QPushButton(self.task5)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.r_button.setFont(font)
        self.r_button.setStyleSheet("border:0px;\n"
"color: black;")
        self.r_button.setObjectName("r_button")
        self.photochanges.addWidget(self.r_button, 0, 3, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.task5)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 351, 487))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.secondimages = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secondimages.sizePolicy().hasHeightForWidth())
        self.secondimages.setSizePolicy(sizePolicy)
        self.secondimages.setText("")
        self.secondimages.setScaledContents(True)
        self.secondimages.setObjectName("secondimages")
        self.horizontalLayout_3.addWidget(self.secondimages)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.photochanges.addWidget(self.scrollArea_2, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.photochanges)
        self.taskManager.addTab(self.task5, "")
        self.task6 = QtWidgets.QWidget()
        self.task6.setObjectName("task6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.task6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.colorChanges = QtWidgets.QSplitter(self.task6)
        self.colorChanges.setOrientation(QtCore.Qt.Horizontal)
        self.colorChanges.setObjectName("colorChanges")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.colorChanges)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.listColor = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.listColor.setObjectName("listColor")
        self.verticalLayout_10.addWidget(self.listColor)
        self.saturationLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.saturationLabel.setObjectName("saturationLabel")
        self.verticalLayout_10.addWidget(self.saturationLabel)
        self.saturationMeasure = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.saturationMeasure.setObjectName("saturationMeasure")
        self.verticalLayout_10.addWidget(self.saturationMeasure)
        self.findColors = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.findColors.setObjectName("findColors")
        self.verticalLayout_10.addWidget(self.findColors)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.colorChanges)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea_4.setMinimumSize(QtCore.QSize(600, 400))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 598, 487))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_5.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_5.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.task6Image = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task6Image.sizePolicy().hasHeightForWidth())
        self.task6Image.setSizePolicy(sizePolicy)
        self.task6Image.setText("")
        self.task6Image.setScaledContents(True)
        self.task6Image.setObjectName("task6Image")
        self.verticalLayout_7.addWidget(self.task6Image)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_8.addWidget(self.scrollArea_4)
        self.verticalLayout_11.addWidget(self.colorChanges)
        self.taskManager.addTab(self.task6, "")
        self.verticalLayout_12.addWidget(self.taskManager)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAction = QtWidgets.QMenu(self.menuFile)
        self.menuAction.setObjectName("menuAction")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFind_the_difference = QtWidgets.QAction(MainWindow)
        self.actionFind_the_difference.setObjectName("actionFind_the_difference")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionFocus_stacking = QtWidgets.QAction(MainWindow)
        self.actionFocus_stacking.setObjectName("actionFocus_stacking")
        self.actionMake_collage = QtWidgets.QAction(MainWindow)
        self.actionMake_collage.setObjectName("actionMake_collage")
        self.actionOptical_Flow = QtWidgets.QAction(MainWindow)
        self.actionOptical_Flow.setObjectName("actionOptical_Flow")
        self.menuAction.addAction(self.actionFocus_stacking)
        self.menuAction.addAction(self.actionMake_collage)
        self.menuAction.addAction(self.actionOptical_Flow)
        self.menuFile.addAction(self.menuAction.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.taskManager.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Фокусна відстань об\'єктива, мм."))
        self.label_6.setText(_translate("MainWindow", "Витрата заряду на фото, %"))
        self.label_5.setText(_translate("MainWindow", "Заряд батареї на момент запуску, %"))
        self.label_7.setText(_translate("MainWindow", "Витрата заряду на 100м, %"))
        self.label_2.setText(_translate("MainWindow", "Допустима висота польоту, м."))
        self.label_8.setText(_translate("MainWindow", "Висота матриці"))
        self.label_4.setText(_translate("MainWindow", "Геометрія  фотосенсора, мм:"))
        self.label_9.setText(_translate("MainWindow", "Ширина матриці"))
        self.label_13.setText(_translate("MainWindow", "Ширина мапи"))
        self.label_12.setText(_translate("MainWindow", "Висота мапи"))
        self.label_11.setText(_translate("MainWindow", "Масштаб мапи, м:"))
        self.pushButton_2.setText(_translate("MainWindow", "Вибрати мапу"))
        self.pushButton.setText(_translate("MainWindow", "Вибрати шлях"))
        self.taskManager.setTabText(self.taskManager.indexOf(self.task1), _translate("MainWindow", "Завдання 1"))
        self.filename_label.setText(_translate("MainWindow", "hello.png"))
        self.r_button_2.setText(_translate("MainWindow", ">"))
        self.taskManager.setTabText(self.taskManager.indexOf(self.task2), _translate("MainWindow", "Завдання 2"))
        self.filename_label_2.setText(_translate("MainWindow", "hello.png"))
        self.r_button_3.setText(_translate("MainWindow", ">"))
        self.longLabel.setText(_translate("MainWindow", "Longitude"))
        self.latLabel.setText(_translate("MainWindow", "Latitude"))
        self.altLabel.setText(_translate("MainWindow", "Altitude"))
        self.rollLabel.setText(_translate("MainWindow", "Roll"))
        self.pitchLabel.setText(_translate("MainWindow", "Pitch"))
        self.yawLabel.setText(_translate("MainWindow", "Yaw"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.taskManager.setTabText(self.taskManager.indexOf(self.task4), _translate("MainWindow", "Завдання 4"))
        self.l_button.setText(_translate("MainWindow", "<"))
        self.r_button.setText(_translate("MainWindow", ">"))
        self.taskManager.setTabText(self.taskManager.indexOf(self.task5), _translate("MainWindow", "Завдання 5"))
        self.saturationLabel.setText(_translate("MainWindow", "Яскравість кольору"))
        self.saturationMeasure.setText(_translate("MainWindow", "0.765413"))
        self.findColors.setText(_translate("MainWindow", "Find the colors"))
        self.taskManager.setTabText(self.taskManager.indexOf(self.task6), _translate("MainWindow", "Завдання 6"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuAction.setTitle(_translate("MainWindow", "Дія"))
        self.actionFind_the_difference.setText(_translate("MainWindow", "Find the difference"))
        self.actionOpen.setText(_translate("MainWindow", "Відкрити"))
        self.actionFocus_stacking.setText(_translate("MainWindow", "Фокус стекінг"))
        self.actionMake_collage.setText(_translate("MainWindow", "Зробити колаж фото"))
        self.actionOptical_Flow.setText(_translate("MainWindow", "Оптичний потік"))

